# Generated by Django 4.0.4 on 2022-05-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etudiant1', models.TextField(max_length=20)),
                ('etudiant2', models.TextField(max_length=20)),
                ('messages', models.TextField(max_length=200000000000000000000000000000000000000)),
            ],
        ),
    ]
