# Generated by Django 4.0.4 on 2022-05-27 18:56

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('wilaya', models.CharField(choices=[('de', ' '), ('Adrar', 'Adrar'), ('Chlef', 'Chlef'), ('Laghouat', 'Laghouat'), ('Oum El Bouaghi', 'Oum El Bouaghi'), ('Batna', 'Batna'), ('Béjaïa', 'Béjaïa'), ('Biskra', 'Biskra'), ('Bechar', 'Bechar'), ('Blida', 'Blida'), ('Bouira', 'Bouira'), ('Tamanrasset', 'Tamanrasset'), ('Tbessa', 'Tbessa'), ('Tlemcen', 'Tlemcen'), ('Tiaret', 'Tiaret'), ('Tizi Ouzou', 'Tizi Ouzou'), ('Alger', 'Alger'), ('Djelfa', 'Djelfa'), ('Jijel', 'Jijel'), ('Sétif', 'Sétif'), ('Saefda', 'Saefda'), ('Skikda', 'Skikda'), ('Sidi Bel Abbes', 'Sidi Bel Abbes'), ('Annaba', 'Annaba'), ('Guelma', 'Guelma'), ('Constantine', 'Constantine'), ('Medea', 'Medea'), ('Mostaganem', 'Mostaganem'), ("M'Sila", "M'Sila"), ('Mascara', 'Mascara'), ('Ouargla', 'Ouargla'), ('Oran', 'Oran'), ('El Bayadh', 'El Bayadh'), ('Illizi', 'Illizi'), ('Bordj Bou Arreridj', 'Bordj Bou Arreridj'), ('Boumerdes', 'Boumerdes'), ('El Tarf', 'El Tarf'), ('Tindouf', 'Tindouf'), ('Tissemsilt', 'Tissemsilt'), ('El Oued', 'El Oued'), ('Khenchela', 'Khenchela'), ('Souk Ahras', 'Souk Ahras'), ('Tipaza', 'Tipaza'), ('Mila', 'Mila'), ('Ain Defla', 'Ain Defla'), ('Naama', 'Naama'), ('Ain Temouchent', 'Ain Temouchent'), ('Ghardaïa', 'Ghardaïa'), ('Relizane', 'Relizane'), (' ', ' ')], default='def', max_length=100, null=True)),
                ('gender', models.CharField(choices=[('homme', 'homme'), ('femme', 'femme')], default='homme', max_length=100)),
                ('year', models.CharField(choices=[('1cp', '1cp'), ('2cp', '2cp'), ('1cs', '1cs'), ('2cs', '2cs'), ('3cs', '3cs')], default='1cp', max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('image', models.ImageField(blank=True, default='media/default.jpg', upload_to='')),
                ('computer_science', models.BooleanField(default=False)),
                ('cyber_security', models.BooleanField(default=False)),
                ('ai', models.BooleanField(default=False)),
                ('design', models.BooleanField(default=False)),
                ('it_systems', models.BooleanField(default=False)),
                ('iot', models.BooleanField(default=False)),
                ('software', models.BooleanField(default=False)),
                ('data_science', models.BooleanField(default=False)),
                ('networks', models.BooleanField(default=False)),
                ('books', models.BooleanField(default=False)),
                ('movies', models.BooleanField(default=False)),
                ('music', models.BooleanField(default=False)),
                ('signing', models.BooleanField(default=False)),
                ('mangas', models.BooleanField(default=False)),
                ('animes', models.BooleanField(default=False)),
                ('series', models.BooleanField(default=False)),
                ('drawing', models.BooleanField(default=False)),
                ('hiking', models.BooleanField(default=False)),
                ('football', models.BooleanField(default=False)),
                ('tennis', models.BooleanField(default=False)),
                ('cooking', models.BooleanField(default=False)),
                ('basketball', models.BooleanField(default=False)),
                ('handball', models.BooleanField(default=False)),
                ('volleyball', models.BooleanField(default=False)),
                ('fitness', models.BooleanField(default=False)),
                ('jogging', models.BooleanField(default=False)),
                ('cyclism', models.BooleanField(default=False)),
                ('note_quizz', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('id_conv', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
