# Generated by Django 4.0.4 on 2022-05-27 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_wilaya'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='cysclism',
            new_name='cyclism',
        ),
    ]
