# Generated by Django 4.0.4 on 2022-05-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_messge', '0002_alter_audio_store_record_alter_audio_store_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio_store',
            name='record',
            field=models.FileField(blank=True, default='media/vocal_test.aac', upload_to=''),
        ),
    ]
